---
title: |
    To-do list  

toc: false
draft: false
---

# Interni to-do list blogu U3V

## Co vylepšit na strankách

- ~~SSL cetifikat na pulpanj.me.cz~~
-   ~~literatura doplnit~~
-   linky do literatury doplnit do postu
-   pridat policka newly added a pole pro logicke razeni do seznamu postu
-   cross reference option (popisky schemat a cislovani)
-   sjednoti captions pro figs a listings
-   zlepsit cislovani rovnic
-   pridat seznamy obrazku kodu a tabulek
-   post fixni body
    -   pavouci diagram doplnit sipky
    -   ~~doplnit definici stabilniho bodu~~
    -   priklad pohyb fce 3. rady s 3 fixnimi body
- rozchodit julia package pro 3D grafiku (Makie, GLMakie)  
    - verze 0.8.1 nefunguje s julia 1.9, ale 0.9.0 ano, ale ta je zatim v beta verzi
- napsat si par funkci 
    - pro rendrovani tabulek do HTML+typst 9hlavičky, formatovani, colorovaní atd.
    - pro standardni grafy
-   nejaky dokument ukazujici jako U3V cist (sekvence postů)
- udelat export vsech clanku do jedne PDF knihy (=> jiny _quarto.yml)


## Náměty ze seancí

-   Optimalizace
    -   ~~muz s pletivem (viz bazen)~~
    -   ~~max. objem pri minimalnim povrchu (viz bazen) ~~ ale jak popsat kouli ?
    -   ~~delka docurani~~ dostrel dela
    -   ~~spojnice 4 mest~~
    -   ~~zachrana tonouciho (+optika)~~
    -   priklad Lagrangeovy multiplikatory
    -   Menelaus's theorem  (trojuhelnik)
- krivky
    - retezovka
    - Brachistochrona 
    - evolventy involventy

-   Minimalni plochy
    - ~~2 bubliny~~
    - rotujici retezovka
    - bublina v krychli
    - Young–Laplace equation for minimal surfaces
-   Kombinatorika
    -   ~~soucet hodu k kostek~~
    -   ~~doba cekani na prvni sestku~~
    -   pravdepodobnost alespon jedne 6-ky pri hodu k kostkami (Demetre)
    - stredni pocet hodu do sekvence 6-6
    - ~~stredni pocet hodu do 6, ale jen kdyz predchozi hody jsou sudé~~
    -  uloha se satnarkou a klobouky
-   Bayes rule
    -   TV soutez s 3 dvermi
-   Statistika
    -   Bernouliho process
    - https://en.wikipedia.org/wiki/Geometric_distribution (bernouli x fury distribution)
    -   nahodna prochazka
        -   pravdepodobnost navratu
        -   pocet zmen znamenka
        -   volebni protokol - pravdepodobnost, ze A bude vzdy vyhravat nad B (reseni (a-b)/(a+b))
    -   ~~Poisonovo rozdeleni priklad s vanocnim testem (limita bernouliho)~~
    -   vymirani slechtickych jmen
    -   zakon velkych cisel
    - volebni protokol (kdy jeden kandidat vede celou dobu scitani)
-   Markovovy retezce
    -   ~~model psu a blech~~
    -   ~~pravdepodobnosti stavu~~
-   Dynamika
    -   Linearni dynamika s diskretnim casem
    -   ~~Nelinearni dynamika s diskretnim casem~~
        -   ~~konvergence, cykly, chaos~~
        -   ~~fixni body~~
        -   ~~bifuračni diagram~~
    -   Dynamika se spojitym casem
        -   Verhusuv model
        -   Riccatiho diferencialni rovnice)
        -   stabilita stabilnich bodu
        -   pohybova rovnice kmitani
        -   vynucene kmity
    krivky
        retezovka <https://en.wikipedia.org/wiki/Catenary>
        brachystoida  <https://cs.wikipedia.org/wiki/Brachistochrona>

-   Informacni entropie
    -   ~~odvozeni bitu pro shodne pravdepodobnosti~~
    -   odvozeni bitu pro neshodne pravdepodobnosti
    -   ~~problem o klokanech~~
    -   ~~uloha o vazeni 12 minci 1 falesna (ma ruznou vahu) kolik vazeni na dvojrammene vaze ji najde ?~~
    -   ~~3-stenna kostka a heatmap entropie/energie~~
    -   reseni pro obecně n energii  ei=i.e1 i=2..n
    -   reseni pro nekonečně  energii
    - entropie pro idealni plyn (spojitá energie)
- Komplexní systémy
    - procesy obnovy (vymíraní příjmení)
    - sypání pisku na hromadu
    - mravenci pochodující k cukru 
    - parkování u divadla
    - nekonečny Markovův řetězec pro 6 po sudých

-   Matematika
        - geometrie
            - pruseciky tecen 3 kruznic (leží na přímce)
            - dukaz pythagorovy vety (ctverec + dukaz zalozeny na skalovani plocha=zvetseni **2 )
        - lin algebra
            - vlastni cisla matice vysvetleni (na 2d matici)
    -   dukaz nekonecneho poctu prvocisel
    -   pingeon princip 

- Bubliny
    -   minimalni plochy klasicke
    -   od minimalnich ploch ke křivosti a diferenciálním rovnicim
    
- napady z praxe/odposlechnuté
    - ~~machacek~~
    - markov retezec prepaid karet Oskar
    - informacni entropie pro prirazovani fraud pripadu spravedlive
    - 2 autobusy na 2 strany jezdi 10 a 50 minutu - jaka je pravdepodobnost jizdy vpravo vlevo
    - velbloudi/banany a přechod pouště
    - pravděpodobnost zastaveni fronty pokud lide maji 0.5 CZK a 1 CZK mince a platí 0,5 CZK 
